### PR TITLE
Avoid using Mocha contexts for variables

### PR DESCRIPTION
**Pull request by jupiter**
https://github.com/mochajs/mocha/issues/1195#issuecomment-96410059

### CODE REVIEW

**Comment by moll** [comment]
Hey,

Thanks for the patch, though would you mind clarifying, why not use context properties? Wouldn't you say they're more suited for the job?

**Comment by jupiter** [comment]
I just replied on the original thread here https://github.com/mochajs/mocha/issues/1195#issuecomment-96410059, which hopefully makes sense.

**Comment by moll** [comment]
Would you feel terrible if I closed this pull request? Like we agreed in https://github.com/mochajs/mocha/issues/1195 I too would prefer Mocha be fixed than work around it.

**Comment by jupiter** [comment]
Not at all. Was really just an example.

**Pull request closed without merging**
