### PR TITLE
Added record functionality

### PR DESCRIPTION
**Pull request by framp**
This pull request adds support for recording requests, piggybacking on mitm.js support for intercepting net calls.

The data is going to be emitted via a `record` event.

Originally opened here: https://github.com/moll/node-mitm/pull/38

### CODE REVIEW

**Comment by amarzavery** [comment]
@moll -  I would like to record some tests so that I can run them in playback mode in travis-ci. Having the recording functionality would be very useful.

Any reason why this has not been merged?

**Comment by darlintonprauchner** [comment]
Hi, we talked earlier, this looks to be what I need, could we get this merged?

**Comment by amarzavery** [comment]
@moll - any updates? Can you please respond?

**Comment by moll** [comment]
Hey, fellows! Apologies for the two year delay. [Time flies when fruit flies](https://en.wikipedia.org/wiki/Time_flies_like_an_arrow;_fruit_flies_like_a_banana), right? :P

Thanks, @framp, for sharing your code! I reckon it could be useful to some! However, this functionality is something I'd rather see either implemented in a library than in Mitm.js itself. Reliable recording seems like a feature with many edge cases and I'm inclined to keep Mitm.js's core fairly light. If you do decide to extract it out, I'd be happy to link to it. @ianwsperber mentions in https://github.com/moll/node-mitm/issues/51 that he'll put something out soon, too.

I'll close the issue here, but the code will fortunately remain here for anyone to take hints from. :)

**Comment by moll** [comment]
Ah, I see I actually wrote roughly the same response a year ago in https://github.com/moll/node-mitm/pull/38. :D Did you end up releasing something, @framp?

**Comment by framp** [comment]
I actually did use it in a project, but never got around to properly releasing due to some testing related issues.
I can't foresee any time in the near future I could dedicate to this but the code in this branch should be a good starting point for anyone who wants to release something.
I'd be happy to give some pointers where needed.

**Comment by ianwsperber** [comment]
@moll @framp @amarzavery @darlintonprauchner  Hi all! I just made public the aforementioned library I've written on top of YesNo that allows one to record requests. It includes a few other features to simplify HTTP mocking. You can find it here: https://github.com/FormidableLabs/yesno

I'll be continuing development over the next month to work toward a stable 1.0 release late November/early December. Would appreciate any feedback you have to offer. I've tried putting together a complete README, but please reach out if anything is confusing. Hopefully it's at least a good first step 😄Thanks!

**Comment by darlintonprauchner** [comment]
It looks pretty interesting, I will play with it later down the week and see what I can find!

Thanks!

**Pull request closed without merging**
